### ISSUE TITLE
Errors in graph stage

### ISSUE THREAD

**Issue by beyang** [alexsaveliev/srclib-antlr#2]
When I run the graph stage on `github.com/phacility/phabricator`, I get a lot of `FileNotFoundException`s and the `.graph.json` file is an empty object. E.g.,

```
2015-11-12 22:28:50,846 [main] INFO LanguageBase - Processing src/applications/legalpad/storage/LegalpadTransactionComment.php
2015-11-12 22:28:50,846 [main] ERROR LanguageBase - Failed to process src/applications/legalpad/storage/LegalpadTransactionComment.php - unexpected error
com.sourcegraph.toolchain.language.ParseException: java.io.FileNotFoundException: LegalpadTransactionComment.php (No such file or directory)
        at com.sourcegraph.toolchain.php.LanguageImpl.parse(LanguageImpl.java:125)
        at com.sourcegraph.toolchain.language.LanguageBase.process(LanguageBase.java:113)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at com.sourcegraph.toolchain.language.LanguageBase.graph(LanguageBase.java:82)
        at com.sourcegraph.toolchain.application.GraphCommand.Execute(GraphCommand.java:74)
        at com.sourcegraph.toolchain.application.Main.main(Main.java:54)
Caused by: java.io.FileNotFoundException: LegalpadTransactionComment.php (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at org.antlr.v4.runtime.misc.Utils.readFile(Utils.java:133)
        at org.antlr.v4.runtime.ANTLRFileStream.load(ANTLRFileStream.java:55)
        at org.antlr.v4.runtime.ANTLRFileStream.<init>(ANTLRFileStream.java:49)
        at org.antlr.v4.runtime.ANTLRFileStream.<init>(ANTLRFileStream.java:44)
        at com.sourcegraph.toolchain.language.LanguageBase.createGrammarConfiguration(LanguageBase.java:271)
        at com.sourcegraph.toolchain.php.LanguageImpl.parse(LanguageImpl.java:117)
        ... 5 more
```

**Comment by alexsaveliev** [comment]
Fixed by alexsaveliev/srclib-antlr@e4d2afb2afb35cf5793e2a55a1148cf738cc23b8
